Create DATABASE LOJA


--MODO SIMPLES GERENCIA O LOG SOZINHO
ALTER DATABASE LOJA SET RECOVERY SIMPLE
WITH NO_WAIT


--REALIZAR BKP FULLL
BACKUP DATABASE LOJA
TO DISK = 'C:\SQL\LOJA_FULL.bak'


--CONFERINDO STATUS NA DATABASE MSDB
SELECT 
A.NAME AS NOME,
A.STATE_DESC AS STATUS,
C.PHYSICAL_DEVICE_NAME  AS LOCALIZACAO_BACKUP,
B.BACKUP_SIZE/1024/1024 AS TAMANHO_MB,
B.BACKUP_FINISH_DATE AS DATA_FINALIZACAO,
B.IS_DAMAGED AS DANIFICADO,
A.RECOVERY_MODEL_DESC AS MODO_RECUPERACAO,
A.IS_AUTO_CLOSE_ON AS AUTO_CLOSE,
A.IS_AUTO_SHRINK_ON AS AUTO_SHIRINK,
A.IS_AUTO_CREATE_STATS_ON AS ESTATISTICA_AUTOMATICAS,
A.IS_AUTO_UPDATE_STATS_ON AS UPDATE_EST_AUTO,
B.SERVER_NAME AS INSTANCIA_SQL,
B.TYPE AS TIPO
FROM SYS.DATABASES A
JOIN MSDB.DBO.BACKUPSET B
ON A.NAME = B.DATABASE_NAME
JOIN MSDB.DBO.BACKUPMEDIAFAMILY C
ON B.MEDIA_SET_ID = C.MEDIA_SET_ID
WHERE A.NAME = 'LOJA'


--BKP LOG
--NÃO EFETUADO POIS ESTA NO MODO SIMPLE
USE MASTER

BACKUP LOG LOJA
TO DISK = 'C:\SQL\LOJA_LOG.trn'

GO

--COLOCANDO EM MODO FULL
ALTER DATABASE LOJA
SET RECOVERY FULL WITH NO_WAIT --NÃO ESPERA AS CONEXÕES ENCERRAREM

-- BACKUP DE LOG
-- NÃO FUNCIONA POIS O PRIUMEIRO BKP FULL FOI REALIZADO EM SIMPLE
BACKUP LOG LOJA
TO DISK = 'C:\SQL\LOJA_LOG.trn'


-- BKP FULL EM MODO FULL
BACKUP DATABASE LOJA
TO DISK = 'C:\SQL\LOJA_FULL.bak'

-- LOG FUNCIONA AGORA 
BACKUP LOG LOJA
TO DISK = 'C:\SQL\LOJA_LOG.trn'

-- VALIDAR BKPS
SELECT A.DATABASE_NAME,
B.PHYSICAL_DEVICE_NAME,
A.BEGINS_LOG_CHAIN,
A.TYPE
FROM MSDB..BACKUPSET A
JOIN MSDB..BACKUPMEDIAFAMILY B
ON A.MEDIA_SET_ID = B.MEDIA_SET_ID
WHERE A.DATABASE_NAME = 'LOJA'


--------- BKP INCREMENTAL
BACKUP LOG LOJA
TO DISK = 'C:\SQL\LOJA_LOG1.trn'

BACKUP LOG LOJA
TO DISK = 'C:\SQL\LOJA_LOG2.trn'

-- VALIDAR BKPS
SELECT A.DATABASE_NAME,
B.PHYSICAL_DEVICE_NAME,
A.BEGINS_LOG_CHAIN,
A.TYPE
FROM MSDB..BACKUPSET A
JOIN MSDB..BACKUPMEDIAFAMILY B
ON A.MEDIA_SET_ID = B.MEDIA_SET_ID
WHERE A.DATABASE_NAME = 'LOJA'

-- BKP DIFERENCIAL
BACKUP DATABASE LOJA
TO DISK = 'C:\SQL\LOJA_DIFF.bak'
WITH DIFFERENTIAL

-- VALIDAR BKPS
SELECT A.DATABASE_NAME,
B.PHYSICAL_DEVICE_NAME,
A.BEGINS_LOG_CHAIN,
A.TYPE
FROM MSDB..BACKUPSET A
JOIN MSDB..BACKUPMEDIAFAMILY B
ON A.MEDIA_SET_ID = B.MEDIA_SET_ID
WHERE A.DATABASE_NAME = 'LOJA'

--RESTORE COM HEADERONLY VERIFICAR VALIDADE DO BKP
RESTORE HEADERONLY
FROM DISK = 'c:\SQL\LOJA_FULL.bak'

--RESTAURANDO OS BKPS PRA UMA DB NOVA
RESTORE DATABASE LOJA_NOVA
FROM DISK = 'C:\SQL\LOJA_FULL.BAK'
WITH FILE = 1,
MOVE N'LOJA' TO 'C:\SQL\LOJA_NOVA.MDF',
MOVE N'LOJA_LOG' TO 'C:\SQL\LOJA_NOVA_LOG.LDF',
NORECOVERY

-- RESTAURAR LOGS
RESTORE LOG LOJA_NOVA
FROM DISK = N'C:\SQL\LOJA_LOG.trn'
WITH FILE = 1,
NORECOVERY
GO
RESTORE LOG LOJA_NOVA
FROM DISK = N'C:\SQL\LOJA_LOG1.TRN'
WITH FILE = 1,
NORECOVERY
GO
RESTORE LOG LOJA_NOVA
FROM DISK = N'C:\SQL\LOJA_LOG2.TRN'
WITH FILE = 1,
NORECOVERY
GO

-- APOS O RESTORE , SUBIR A DB 
RESTORE DATABASE LOJA_NOVA
WITH RECOVERY

--VERIFICANDO HISTORICO DE BACKUPS
SELECT * FROM MSDB..RESTOREHISTORY
