
--CRIAÇÃO DE BANCO DE DADOS
CREATE DATABASE CLIENTES
ON PRIMARY
(NAME = N'CLIENTE', FILENAME = N'C:\SQL\CLIENTE_DADOS.MDF')
LOG ON
(NAME = N'CLIENTELOG', FILENAME = N'C:\SQL\CLIENTE_LOG.LDF')
GO
--CRIA TABELA
USE CLIENTES
GO
CREATE TABLE CLIENTES(
 NAME VARCHAR(30),
 CATEGORIA VARCHAR(30)
)
GO

--INSERCAO DE DADOS
INSERT INTO CLIENTES VALUES ('SONY','ELETRONICOS'),
('MICROSOFT','SOFTWARE')
GO

--REALIAZANDO O BACKUP FULL
BACKUP DATABASE CLIENTES
TO DISK = N'C:\SQL\CLIENTES_FULL.BAK'
GO

--ADICIONANDO MAIS REGISTROS
INSERT INTO CLIENTES VALUES ('GOOGLE','WEB'),
('ASUS','ELETRONICOS')
GO

--PRIMEIRO BACKUP DE LOG
BACKUP LOG CLIENTES
TO DISK = 'C:\SQL\CLIENTES_LOG1.TRN'
GO

--ADICIONANDO MAIS DOIS REGISTROS
INSERT INTO CLIENTES VALUES ('DUFRY','VAREJO'),
('TERA','TECNOLOGIA')
GO

--SEGUNDO BACKUP DE LOG
BACKUP LOG CLIENTES
TO DISK = 'C:\SQL\CLIENTES_LOG2.TRN'
GO

--INSERINDO MAIS DOIS REGISTROS
INSERT INTO CLIENTES VALUES ('MERCEDES','AUTOMOVEIS'),
('NIKE','ESPORTES')
GO


--TERCEIRO BACKUP DE LOG
BACKUP LOG CLIENTES
TO DISK = 'C:\SQL\CLIENTES_LOG3.TRN'
GO

--INSERINDO MAIS DOIS REGISTROS
INSERT INTO CLIENTES VALUES ('TIM','TELEFONIA'),
('MACDONALDS','FASTFOOD')
GO

--VERIFICANDO OS REGISTROS INSERIDOS NA TABELA
--TEMOS 10 CLIENTES (AQUI)
SELECT * FROM CLIENTES
GO

--COLOCANDO A DATABASE OFFLINE PARA REMOVER O MDF
USE MASTER
ALTER DATABASE CLIENTES
SET OFFLINE
WITH ROLLBACK IMMEDIATE
GO

--APAGANDO O MDF
EXEC XP_CMDSHELL 'DEL C:\SQL\CLIENTES_DADOS.MDF'
GO

--TENTATIVA DE COLOCAR A DATABASE ONLINE
ALTER DATABASE CLIENTES
SET ONLINE
GO

--VERIFICANDO HISTORICO DE LOGS DE ERROS
sp_readerrorlog

--RESTAURANDO O BACKUP FULL
RESTORE DATABASE CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_FULL.BAK'
WITH MOVE N'CLIENTE' TO 'C:\SQL\CLIENTE_DADOS_NOVO.MDF',
MOVE N'CLIENTELOG' TO 'C:\SQL\CLIENTE_LOG_NOVO.LDF',
REPLACE, RECOVERY
GO


USE CLIENTES_NOVA
SELECT * FROM CLIENTES
GO
--COLOCANDO A DATABASE EM MODO DE SINGLE USER
--PARA RESTAURAR OS LOGS
USE MASTER

ALTER DATABASE CLIENTES_NOVA
SET SINGLE_USER WITH ROLLBACK IMMEDIATE

--ATENCAO COM O NO RECOVERY
RESTORE DATABASE CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_FULL.BAK'
WITH MOVE N'CLIENTE' TO 'C:\SQL\CLIENTE_DADOS_NOVO.MDF',
MOVE N'CLIENTELOG' TO 'C:\SQL\CLIENTE_LOG_NOVO.LDF',
REPLACE, NORECOVERY
GO

--VERIFICANDO O STATUS
SELECT NAME, STATE_DESC FROM SYS.DATABASES
WHERE NAME IN ('CLIENTES','CLIENTES_NOVA')
GO

--RESTAURANDO OS LOGS
RESTORE LOG CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_LOG1.TRN'
WITH NORECOVERY


RESTORE LOG CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_LOG2.TRN'
WITH NORECOVERY


RESTORE LOG CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_LOG3.TRN'
WITH RECOVERY

--VERIFICANDO OS DADOS
USE CLIENTES_NOVA
SELECT * FROM CLIENTES

--TAIL OF LOG
BACKUP LOG CLIENTES
TO DISK = N'C:\SQL\CLIENTES_TAIL.TRN'
GO

--FORCANDO O BACKUP COM A FALTA DO DATAFILE
BACKUP LOG CLIENTES
TO DISK = N'C:\SQL\CLIENTES_TAIL.TRN'
WITH CONTINUE_AFTER_ERROR
GO

--COLOCANDO A DATABASE OFFLINE
USE MASTER
ALTER DATABASE CLIENTES_NOVA
SET SINGLE_USER
WITH ROLLBACK IMMEDIATE

--RESTORE DO TAIL OF LOG
RESTORE DATABASE CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_FULL.BAK'
WITH MOVE N'CLIENTE' TO 'C:\SQL\CLIENTES_DADOS_NOVO.MDF',
MOVE N'CLIENTELOG' TO 'C:\SQL\CLIENTES_LOG_NOVO.LDF',
REPLACE, NORECOVERY
GO
RESTORE DATABASE CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_LOG1.TRN'
WITH NORECOVERY
GO
RESTORE DATABASE CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_LOG2.TRN'
WITH NORECOVERY
GO
RESTORE DATABASE CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_LOG3.TRN'
WITH NORECOVERY
GO
RESTORE DATABASE CLIENTES_NOVA
FROM DISK = 'C:\SQL\CLIENTES_TAIL.TRN'
WITH RECOVERY
GO
--VERIFICANDO OS DADOS
USE CLIENTES_NOVA
SELECT * FROM CLIENTES
GO

ALTER DATABASE CLIENTES_NOVA
SET MULTI_USER